### ISSUE TITLE
ZZZ Daily Check-In not taken into account

### ISSUE THREAD

**Issue by HiroLeWeeb** [sglkc/hoyolab-auto-daily#16]
Hi!
I'm kind of new to Github Actions, and decided to give it a try on Nov 14.
I did setup everything correctly, double checked cookies and discord webhook link and it was checking out.
I had the webhook text every day, but I realized just now that I did not get any in-game mail.

After checking the reward history on the website, I saw that it did not count anything at all, despite saying that it was successful.
![image](https://github.com/user-attachments/assets/7f2daf51-bb0f-4556-ae70-464688a2bdb6)

Am I missing something? 
Thanks in advance !

**Comment by sglkc** [comment]
I took a quick look to your workflow,
on 14 Nov you didn't set the GAMES variable properly so it didn't check in for you.
![Screenshot_2024_1119_140243](https://github.com/user-attachments/assets/1c139083-f7e9-4e19-bd6f-724db4e2731d)

Now you have the right GAMES set, it checks out for you.
![Screenshot_2024_1119_140323](https://github.com/user-attachments/assets/6b80b078-7078-467d-8e15-a79c39f27c70)

The error (at account 2 check in) is caused by having the wrong cookie or you entered an additional newline when setting COOKIE in the env variable 

anyways, it should work as expected tomorrow

**Comment by HiroLeWeeb** [comment]
Yeah I figured it out right after typing this out, but was sure it was still saved as a draft.
Now webhook reports it correctly.
Anyway, thanks for that!
